### ISSUE TITLE
Deprecated functions in iOS 9

### ISSUE THREAD

**Issue by fbara** [zakkhoyt/VWWPermissionKit#20]
When building against iOS 9.0, I received many deprecation warnings for files in this screenshot:
![pods xcodeproj 2015-11-12](https://cloud.githubusercontent.com/assets/5705015/11134079/c794308a-895f-11e5-9bd8-b9b8b809c72a.jpg)

**Comment by zakkhoyt** [comment]
Thx for the report. I'm working on the next release which will remove these warnings.

**Comment by zakkhoyt** [comment]
This has been fixed in 1.3.0. See the master branch readme for details or just update your Podfile to:

pod 'VWWPermissionKit', '~> 1.3.0'
