### ISSUE TITLE
YSK, Apple is denying apps that include includes to healthkit and homekit if your app doesn't have those features

### ISSUE THREAD

**Issue by bwildedaniel** [zakkhoyt/VWWPermissionKit#21]

**Comment by iamelie** [comment]
+1
CAUTION to use. It was happened to me too.

**Comment by metasmile** [comment]
+1
CAUTION to use. It was happened to me too.

**Comment by zakkhoyt** [comment]
Thanks for your input. I will post this issue right at the top of the README.md until I can implement a fix.

**Comment by zakkhoyt** [comment]
For now I've removed HealthKit support. Homekit support was not yet implemented. If you wish to try to submit your app you can modify your Podfile to:

pod 'VWWPermissionKit', :git => 'https://github.com/zakkhoyt/VWWPermissionKit', :branch => 'approval'

I will work on an official release shortly.

**Comment by zakkhoyt** [comment]
Okay, I have made an official new release which has removed HealthKit and HomeKit was well as removed support for ALAssetsLIbrary (deprecated by apple) which is replaced with Photos. Also removed the old ABAddressBook replacing it with the new Contacts framework. 

pod 'VWWPermissionKit', '~> 1.3.0'

I will look into a way to include HealthKit once again but will take a little more time
